os: Visual Studio 2015
environment:
  MSYSTEM: MINGW64
  matrix:

    # For Python versions available on Appveyor, see
    # http://www.appveyor.com/docs/installed-software#python
    # The list here is complete (excluding Python 2.6, which
    # isn't covered by this document) at the time of writing.

    - PYTHON: "C:\\Python36-x64"

  global:
      CONDA_INSTALL_LOCN: C:\\Miniconda36-x64

install:
  # We need wheel installed to build wheels
  - set PATH=%PYTHON_PATH%;%PYTHON_PATH%\Scripts;C:\msys64\usr\bin;%PATH%
  - set PATH=C:\Python36-x64;%PATH%
  #- bash -lc ""
  #- bash -lc "pacman --noconfirm --needed -Sy bash pacman pacman-mirrors msys2-runtime msys2-runtime-devel"
  #- bash -lc "rm -f /mingw64/etc/gdbinit"
  #- bash -lc "pacman -Ss lapack"
  #- bash -lc "pacman --noconfirm -S mingw-w64-x86_64-{gcc,gcc-ada,gcc-fortran,gcc-libgfortran,gcc-objc,cmake,make,zlib,lapack,openblas}"
  - mkdir "lib"
  - mkdir "include"
  - echo "%cd%\include"
  - move "lapacke.h" "include\lapacke.h"
  - ps: Start-FileDownload "https://icl.cs.utk.edu/lapack-for-windows/libraries/VisualStudio/3.7.0/Dynamic-MINGW/Win64/liblapacke.dll" -FileName "lib\liblapacke.dll"
  #- copy "lib\liblapacke.dll" "libact\query_strategies\liblapacke.dll"
  - ps: Start-FileDownload "https://icl.cs.utk.edu/lapack-for-windows/libraries/VisualStudio/3.7.0/Dynamic-MINGW/Win64/liblapacke.lib" -FileName "lib\liblapacke.lib"
  - ps: Start-FileDownload "https://icl.cs.utk.edu/lapack-for-windows/libraries/VisualStudio/3.7.0/Dynamic-MINGW/Win64/liblapack.dll" -FileName "lib\liblapack.dll"
  #- copy "lib\liblapack.dll" "libact\query_strategies\liblapack.dll"
  - ps: Start-FileDownload "https://icl.cs.utk.edu/lapack-for-windows/libraries/VisualStudio/3.7.0/Dynamic-MINGW/Win64/liblapack.lib" -FileName "lib\liblapack.lib"
  - ps: Start-FileDownload "https://icl.cs.utk.edu/lapack-for-windows/libraries/VisualStudio/3.7.0/Dynamic-MINGW/Win64/libblas.dll" -FileName "lib\libblas.dll"
  #- copy "lib\libblas.dll" "libact\query_strategies\libblas.dll"
  - ps: Start-FileDownload "https://icl.cs.utk.edu/lapack-for-windows/libraries/VisualStudio/3.7.0/Dynamic-MINGW/Win64/libblas.lib" -FileName "lib\libblas.lib" 
  - ps: Start-FileDownload "http://icl.cs.utk.edu/lapack-for-windows/libraries/CLAPACK/lapack.lib" -FileName "lib\lapack.lib"
  - ps: Start-FileDownload "http://icl.cs.utk.edu/lapack-for-windows/libraries/CLAPACK/blas.lib" -FileName "lib\blas.lib"
  - ps: Start-FileDownload "http://icl.cs.utk.edu/lapack-for-windows/libraries/CLAPACK/libf2c.lib" -FileName "lib\libf2c.lib"
  - ps: Start-FileDownload "http://icl.cs.utk.edu/lapack-for-windows/include/clapack.h" -FileName "include\clapack.h"
  - ps: Start-FileDownload "http://icl.cs.utk.edu/lapack-for-windows/include/f2c.h" -FileName "include\f2c.h"
  #- ps: Start-FileDownload "https://icl.cs.utk.edu/lapack-for-windows/include/lapacke.h" -FileName "include\lapacke.h"
  - ps: Start-FileDownload "https://icl.cs.utk.edu/lapack-for-windows/include/lapacke_mangling.h" -FileName "include\lapacke_mangling.h"
  - ps: Start-FileDownload "https://icl.cs.utk.edu/lapack-for-windows/include/lapacke_config.h" -FileName "include\lapacke_config.h"
  - ps: Start-FileDownload "https://icl.cs.utk.edu/lapack-for-windows/include/lapacke_utils.h" -FileName "include\lapacke_utils.h"

  - "%PYTHON%\\python.exe -m pip install wheel"
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt"
  #- "call %CONDA_INSTALL_LOCN%\\Scripts\\activate.bat"
  #- "conda config --add channels conda-forge --force"
  #- "conda install -y lapack"
  #- call "C:\Program Files (x86)\Microsoft Visual Studio 17.0\VC\vcvarsall.bat" amd64
  #- set "LIB=%CONDA_INSTALL_LOCN%\\Library\lib;%LIB%"
  #- set "CPATH=%CONDA_INSTALL_LOCN%\\Library\include;%CPATH%"
  #- set "INCLUDE=%CONDA_INSTALL_LOCN%\\Library\include;%INCLUDE%"
  - set "LIB=%cd%\lib;%LIB%"
  - set "LIBPATH=%cd%\lib;%LIBPATH%"
  - set "PATH=%cd%\lib;%PATH%"
  - set "PATH=%cd%\libact\query_strategies;%PATH%"
  - set "PYTHONPATH=%cd%\libact\query_strategies;%cd%\lib;%PYTHONPATH%"
  - set "PYTHON_PATH=%cd%\libact\query_strategies;%PYTHON_PATH%"
  - dir "%cd%\libact\query_strategies"
  - set "CPATH=%cd%\include;%CPATH%"
  - set "INCLUDE=%cd%\include;%INCLUDE%"
  #- call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64

build: off

test_script:
  # Put your test command here.
  # If you don't need to build C extensions on 64-bit Python 3.3 or 3.4,
  # you can remove "build.cmd" from the front of the command, as it's
  # only needed to support those cases.
  # Note that you must use the environment variable %PYTHON% to refer to
  # the interpreter you're using - Appveyor does not do anything special
  # to put the Python version you want to use on PATH.
  #- set "LIB=%CONDA_INSTALL_LOCN%\\Library\lib;%LIB%"
  #- set "CPATH=%CONDA_INSTALL_LOCN%\\Library\include;%CPATH%"
  #- set "INCLUDE=%CONDA_INSTALL_LOCN%\\Library\include;%INCLUDE%"
  #- set "PATH=C:\msys64\mingw64\bin;%PATH%"
  - "%PYTHON%\\python.exe setup.py build"
  - dir "%cd%\build\lib.win-amd64-3.6\libact\query_strategies"
  - dumpbin /dependents "%cd%\build\lib.win-amd64-3.6\libact\query_strategies\_variance_reduction.cp36-win_amd64.pyd"
  - where liblapack.dll
  - where python
  - where python36.dll
  - where KERNEL32.dll
  - where VCRUNTIME140.dll
  - where api-ms-win-crt-stdio-l1-1-0.dll
  - where api-ms-win-crt-heap-l1-1-0.dll
  - where api-ms-win-crt-runtime-l1-1-0.dll
  - set "PYTHONPATH=%cd%\build\lib.win-amd64-3.6\libact\query_strategies;%PYTHONPATH%"
  - echo %PYTHONPATH%
  - "%PYTHON%\\python.exe setup.py test"

after_test:
  # This step builds your wheels.
  # Again, you only need build.cmd if you're building C extensions for
  # 64-bit Python 3.3/3.4. And you need to use %PYTHON% to get the correct
  # interpreter
  - set PATH=C:\msys64\mingw64\bin;%PATH%
  - "%PYTHON%\\python.exe setup.py bdist_wheel"

artifacts:
  # bdist_wheel puts your built wheel in the dist directory
  - path: dist\*
  - path: build\*

#on_success:
#  You can use this step to upload your artifacts to a public website.
#  See Appveyor's documentation for more details. Or you can simply
#  access your wheels from the Appveyor "artifacts" tab for your build.
